local colors = require("themes").getCurrentTheme()

return {
  DevIconDefault = { fg = colors.color7 },
  DevIconc = { fg = colors.color12 },
  DevIconcss = { fg = colors.color12 },
  DevIcondeb = { fg = colors.color6 },
  DevIconDockerfile = { fg = colors.color6 },
  DevIconhtml = { fg = colors.color9 },
  DevIconjpeg = { fg = colors.color2 },
  DevIconjpg = { fg = colors.color2 },
  DevIconjs = { fg = colors.color11 },
  DevIconkt = { fg = colors.color4 },
  DevIconlock = { fg = colors.color4 },
  DevIconmp3 = { fg = colors.color1 },
  DevIconmp4 = { fg = colors.color1 },
  DevIconout = { fg = colors.color1 },
  DevIconpng = { fg = colors.color2 },
  DevIconpy = { fg = colors.color4 },
  DevIcontoml = { fg = colors.color4 },
  DevIconts = { fg = colors.color12 },
  DevIconttf = { fg = colors.color15 },
  DevIconrb = { fg = colors.color9 },
  DevIconrpm = { fg = colors.color11 },
  DevIconvue = { fg = colors.color2 },
  DevIconwoff = { fg = colors.color15 },
  DevIconwoff2 = { fg = colors.color15 },
  DevIconxz = { fg = colors.color11 },
  DevIconzip = { fg = colors.color11 },
  DevIconZig = { fg = colors.color9 },
}
