local colors = require("themes").getCurrentTheme()

return {
  Normal = { fg = colors.foreground, bg = colors.background },
  SignColumn = { bg = colors.background, fg = colors.background },
  MsgArea = { fg = colors.foreground, bg = colors.background },
  ModeMsg = { fg = colors.foreground, bg = colors.background },
  MsgSeparator = { fg = colors.foreground, bg = colors.background },
  SpellBad = { fg = colors.color2 },
  SpellCap = { fg = colors.color12 },
  SpellLocal = { fg = colors.color12 },
  SpellRare = { fg = colors.color4 },
  NormalNC = { fg = colors.foreground, bg = colors.background },
  WildMenu = { fg = colors.color7, bg = colors.color4 },
  AbsoluteDark = { bg = colors.darker, fg = colors.foreground },
  AbsoluteCursor = { bg = colors.cursorline, fg = colors.foreground },
  CursorLineNr = { fg = colors.fg },
  Comment = { fg = colors.comment, italic = true },
  Folded = { fg = colors.color4, bg = colors.background },
  FoldColumn = { fg = colors.color12, bg = colors.background },
  LineNr = { fg = colors.color8, bg = colors.background },
  FloatBorder = { fg = colors.foreground, bg = colors.background },
  Whitespace = { fg = colors.color1 },
  VertSplit = { fg = colors.darker, bg = colors.darker },
  CursorLine = { bg = colors.background },
  CursorColumn = { bg = colors.background },
  ColorColumn = { bg = colors.background },
  NormalFloat = { bg = colors.background },
  Visual = { bg = colors.color0, fg = colors.foreground },
  VisualNOS = { bg = colors.background },
  WarningMsg = { fg = colors.color3, bg = colors.background },
  DiffAdd = { bg = colors.background, fg = colors.color12 },
  DiffChange = { bg = colors.background, fg = colors.color5 },
  DiffDelete = { bg = colors.background, fg = colors.color1 },
  QuickFixLine = { bg = colors.color2 },
  MatchParen = { fg = colors.color12, bg = colors.background },
  Cursor = { fg = colors.comment, bg = colors.cursor },
  lCursor = { fg = colors.foreground, bg = colors.cursor },
  CursorIM = { fg = colors.foreground, bg = colors.cursor },
  TermCursor = { fg = colors.foreground, bg = colors.cursor },
  TermCursorNC = { fg = colors.foreground, bg = colors.cursor },
  Conceal = { fg = colors.color4, bg = colors.background },
  Directory = { fg = colors.color12 },
  SpecialKey = { fg = colors.color12 },
  Title = { fg = colors.color11 },
  ErrorMsg = { fg = colors.color1, bg = colors.background },
  Search = { fg = colors.background, bg = colors.color10 },
  IncSearch = { fg = colors.background, bg = colors.color11 },
  Substitute = { fg = colors.color3, bg = colors.color12 },
  MoreMsg = { fg = colors.color5 },
  Question = { fg = colors.color5 },
  EndOfBuffer = { fg = colors.background },
  NonText = { fg = colors.color1 },
  Variable = { fg = colors.color5 },
  String = { fg = colors.color10 },
  Character = { fg = colors.color12 },
  Constant = { fg = colors.color12 },
  Number = { fg = colors.color12 },
  Boolean = { fg = colors.color5 },
  Float = { fg = colors.color12 },
  Identifier = { fg = colors.color1 },
  Function = { fg = colors.color12 },
  Operator = { fg = colors.color12 },
  Type = { fg = colors.color12 },
  StorageClass = { fg = colors.color3 },
  Structure = { fg = colors.color12 },
  Typedef = { fg = colors.color5 },
  Keyword = { fg = colors.color5 },
  Statement = { fg = colors.color5 },
  Conditional = { fg = colors.color1 },
  Repeat = { fg = colors.color5 },
  Label = { fg = colors.color12 },
  Exception = { fg = colors.color7 },
  Include = { fg = colors.color1 },
  PreProc = { fg = colors.color12 },
  Define = { fg = colors.color12 },
  Macro = { fg = colors.color12 },
  PreCondit = { fg = colors.color12 },
  Special = { fg = colors.color12 },
  SpecialChar = { fg = colors.color12 },
  Tag = { fg = colors.color15 },
  Debug = { fg = colors.color13 },
  Delimiter = { fg = colors.color7 },
  SpecialComment = { fg = colors.color8 },
  Ignore = { fg = colors.color7, bg = colors.background },
  Todo = { fg = colors.color1, bg = colors.background },
  Error = { fg = colors.color3, bg = colors.background },
  TabLine = { fg = colors.color2, bg = colors.background },
  TabLineSel = { fg = colors.foreground, bg = colors.background },
  TabLineFill = { fg = colors.foreground, bg = colors.background },
}
