#!/run/current-system/sw/bin/bash

BLURTOGGLE=$(hyprctl getoption animations:enabled | awk 'NR==2{print $2}')

if [ "$BLURTOGGLE" = 1 ]; then
  hyprctl --batch "keyword decoration:blur:enabled 0"
  exit
else
  hyprctl --batch "keyword decoration:blur:enabled 1"
fi
hyprctl reload
