#!/run/current-system/sw/bin/bash
HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==2{print $2}')
if [ "$HYPRGAMEMODE" = 1 ] ; then
    hyprctl --batch "\
        keyword decoration:blur:enabled 0"
    exit
fi

hyprctl reload
